export const PRODUCT_REQUEST="PRODUCT_REQUEST";
export const PRODUCT_FAILURE="PRODUCT_FAILURE";
export const PRODUCT_SUCCESS="PRODUCT_SUCCESS";
export const ADD_PRODUCT="ADD_PRODUCT";
export const PATCH_PRODUCT_SUCCESS="PATCH_PRODUCT_SUCCESS";

